### ISSUE TITLE
Wyzeapy time related code not transportable and get_event_list possibly have a design flaw

### ISSUE THREAD

**Issue by faanskit** [JoshuaMulliken/wyzeapy#4]
**Issue 1**
In `get_event_list()` in `base_client.py`, the following time functions is used:

`            "begin_time": int(str(datetime.date.today().strftime("%s")) + "000"),
`

`strftime("%s")` is not supported on Windows. For more info what is supported for [strftime()](url), see this [link](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?redirectedfrom=MSDN&view=msvc-160).

This results in the following error on Windows:
```
Traceback (most recent call last):

  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\wyzeapy\client.py", line 237, in get_latest_event
    raw_events = self.client.get_event_list(device, 10)['data']['event_list']
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\wyzeapy\base_client.py", line 432, in get_event_list
    "begin_time": int(str(datetime.date.today().strftime("%s")) + "000"),

ValueError: Invalid format string
```

**Issue 2**
This method also has a built in flaw. Possible number of events differs depending of time-of-day. 1am will only provide 1hrs of possible hits, but 11pm will provide 23hrs of possible hits.

Propose to change to a function relative to now. Suppose 2hrs x 60 minutes x 60 seconds should be enough.
`            "begin_time": int(str(int(time.time() - (2 * 60 * 60))) + "000"),
`

This should fix both issue as time.time() is transportable, and the function now works as intended (?)

**Comment by faanskit** [comment]
Sure, can I also add "2" to this list? Captures also sound events from cameras.

            "event_value_list": [
                "1",
                "2",
                "13",
                "10",
                "12"

**Comment by JoshuaMulliken** [comment]
Do we want sound? For the cameras I think users would only want the device to trigger on motion. 

That is the understanding of the feature right now.

**Comment by JoshuaMulliken** [comment]
Ok, lets see if we can get feedback from some other stakeholders. Maybe this needs to be configurable in some way. I am not sure how that would be implemented but depending on what the other community members think we can consider our options.
